config/routes.rb
SingaporeStories::Application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'static#home'

  namespace :api, defaults: {format: 'json'} do
    resources :testimonies
  end

  get 'people/:id/testimonies' => 'people#user_testimonies', as: :mytestimonies

  devise_for :people
  devise_scope :person do
    get '/sign-in' => "devise/sessions#new", :as => :login
    get '/sign-out' => "devise/sessions#destroy", :as => :logout
  end

  resources :people
  resources :tags
  resources :testimonies

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/person.rb
class Person < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  has_many :testimonies

  has_many :friendships
  has_many :friends, :through => :friendships, :source => :friend_person

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy, :user_testimonies]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  def user_testimonies
    tlist = @person.testimonies
    render json: (build_testimonies(tlist))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:nickname, :arrival_date, :sex, :exit_date, :birthday)
    end

    def build_testimonies t_list
      final_struct = []
      t_list.each do |t|
        tmp_struct = {}
        tmp_struct[:id] = t.id
        tmp_struct[:date] = t.story_date
        tmp_struct[:location] = {
          latitude: t.lat,
          longitude: t.lon
        }
        tmp_struct[:memory] = t.memory
        tmp_struct[:image_url] = t.image_url
        final_struct << tmp_struct
      end
      final_struct
    end
end

app/views/people/_form.html.haml
= form_for @person, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :nickname, :class => 'control-label'
    .controls
      = f.text_field :nickname, :class => 'text_field'
  .control-group
    = f.label :arrival_date, :class => 'control-label'
    .controls
      = f.text_field :arrival_date, :class => 'text_field'
  .control-group
    = f.label :sex, :class => 'control-label'
    .controls
      = f.text_field :sex, :class => 'text_field'
  .control-group
    = f.label :exit_date, :class => 'control-label'
    .controls
      = f.text_field :exit_date, :class => 'text_field'
  .control-group
    = f.label :birthday, :class => 'control-label'
    .controls
      = f.text_field :birthday, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), people_path, :class => 'btn'

app/views/people/edit.html.haml
- model_class = Person
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/people/index.html.haml
- model_class = Person
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:nickname)
      %th= model_class.human_attribute_name(:arrival_date)
      %th= model_class.human_attribute_name(:sex)
      %th= model_class.human_attribute_name(:exit_date)
      %th= model_class.human_attribute_name(:birthday)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @people.each do |person|
      %tr
        %td= link_to person.id, person_path(person)
        %td= person.nickname
        %td= person.arrival_date
        %td= person.sex
        %td= person.exit_date
        %td= person.birthday
        %td=l person.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_person_path(person), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), person_path(person), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_person_path, :class => 'btn btn-primary'

app/views/people/new.html.haml
- model_class = Person
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/people/show.html.haml
- model_class = Person
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:nickname) + ':'
  %br
  = @person.nickname
%p
  %strong= model_class.human_attribute_name(:arrival_date) + ':'
  %br
  = @person.arrival_date
%p
  %strong= model_class.human_attribute_name(:sex) + ':'
  %br
  = @person.sex
%p
  %strong= model_class.human_attribute_name(:exit_date) + ':'
  %br
  = @person.exit_date
%p
  %strong= model_class.human_attribute_name(:birthday) + ':'
  %br
  = @person.birthday

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), people_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_person_path(@person), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), person_path(@person), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'