config/routes.rb
SingaporeStories::Application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'static#home'

  namespace :api, defaults: {format: 'json'} do
    resources :testimonies
  end

  get 'people/:id/testimonies' => 'people#user_testimonies', as: :mytestimonies

  devise_for :people
  devise_scope :person do
    get '/sign-in' => "devise/sessions#new", :as => :login
    get '/sign-out' => "devise/sessions#destroy", :as => :logout
  end

  resources :people
  resources :tags
  resources :testimonies

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/testemonies/edit.html.haml
- model_class = Testemony
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/testemonies/index.html.haml
- model_class = Testimony
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:lat)
      %th= model_class.human_attribute_name(:lon)
      %th= model_class.human_attribute_name(:story_date)
      %th= model_class.human_attribute_name(:memory)
      %th= model_class.human_attribute_name(:audio_url)
      %th= model_class.human_attribute_name(:image_url)
      %th= model_class.human_attribute_name(:video_url)
      %th= model_class.human_attribute_name(:person_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @testimonies.each do |testimony|
      %tr
        %td= link_to testimony.id, testimony_path(testimony)
        %td= testimony.lat
        %td= testimony.lon
        %td= testimony.story_date
        %td= testimony.memory
        %td= testimony.audio_url
        %td= testimony.image_url
        %td= testimony.video_url
        %td= testimony.person_id
        %td=l testimony.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_testimony_path(testimony), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), testimony_path(testimony), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_testimony_path, :class => 'btn btn-primary'