config/routes.rb
SingaporeStories::Application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'static#home'

  namespace :api, defaults: {format: 'json'} do
    resources :testimonies
  end

  get 'people/:id/testimonies' => 'people#user_testimonies', as: :mytestimonies

  devise_for :people
  devise_scope :person do
    get '/sign-in' => "devise/sessions#new", :as => :login
    get '/sign-out' => "devise/sessions#destroy", :as => :logout
  end

  resources :people
  resources :tags
  resources :testimonies

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Imago Singapura"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    %link{:rel => 'stylesheet', :href => "https://api.tiles.mapbox.com/mapbox.js/v2.1.1/mapbox.css"}
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.png', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    - if !current_person.nil?
      #wrapper
        #sidebar-wrapper
          %ul.sidebar-nav
            %li.sidebar-brand
              %a.current#home-nav(href="/#/")
            %hr
            -# %li
            -#   %a#profile-nav(href="#{person_path(current_person)}")
            %li
              %a#profile-nav(href="/#/testimonies/grid")
            %li
              %a#map-nav(href="/#/testimonies/map")

          %ul.sidebar-nav-bottom
            %li
              %a#logout(href="#{logout_path}") Logout

        #page-content-wrapper
          .container-fluid
            .row
              .col-lg-12#main-view-container
                = yield
    - else
      #wrapper
        .container-fluid
          .row
            .col-lg-12#container
              = yield


  %script{:src=>"https://api.tiles.mapbox.com/mapbox.js/v2.1.1/mapbox.js"}